apiVersion: v1
data:
  db_pass: dGhpc2lzYXRlc3R0aGluZy4=
  password: dGhpc2lzYXRlc3R0aGluZy4=
  username: YWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"dGhpc2lzYXRlc3R0aGluZy4=","username":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{},"name":"admin-login-secrets","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2023-04-13T17:02:11Z"
  name: admin-login-secrets
  namespace: default
  resourceVersion: "563"
  uid: dcdba43e-d3f3-4a77-9232-22f2f890af44
type: Opaque