apiVersion: v1
kind: Secret
metadata:
  name: admin-login-secrets
type: Opaque
data:
  username: |-
    {{- with (printf "%s" "secrets.txt") }}
    {{ . | readFile | b64enc }}
    {{- end }}
  password: |-
    {{- with (printf "%s" "secrets.txt") }}
    {{ index (split (readFile .) "\n") 1 | trim | b64enc }}
    {{- end }}
